# Generated by Django 5.1.3 on 2024-11-21 20:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_alter_product_description'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='numInStock',
            new_name='countInStock',
        ),
    ]
